from typing import Any
from typing import Union

from numpy.core._multiarray_umath import ndarray


def _flag_red(x: {__mul__}) -> float: ...


def _flag_green(x: {__mul__}) -> None: ...


def _flag_blue(x: {__mul__}) -> float: ...


def _prism_red(x: {__mul__}) -> float: ...


def _prism_green(x: {__mul__}) -> float: ...


def _prism_blue(x: {__mul__}) -> float: ...


def _ch_helper(gamma: Any,
               s: {__truediv__},
               r: {__mul__},
               h: {__mul__},
               p0: {__mul__},
               p1: {__mul__},
               x: {__pow__}) -> Union[float, Any]: ...


def cubehelix(gamma: float = 1.0,
              s: float = 0.5,
              r: float = -1.5,
              h: float = 1.0) -> dict[str, partial[Union[float, Any]]]: ...


def _g0(x: Any) -> int: ...


def _g1(x: Any) -> float: ...


def _g2(x: Any) -> int: ...


def _g3(x: Any) -> Any: ...


def _g4(x: {__pow__}) -> Any: ...


def _g5(x: {__pow__}) -> Any: ...


def _g6(x: {__pow__}) -> Any: ...


def _g7(x: Any) -> None: ...


def _g8(x: Any) -> None: ...


def _g9(x: {__mul__}) -> None: ...


def _g10(x: {__mul__}) -> None: ...


def _g11(x: {__sub__}) -> None: ...


def _g12(x: Any) -> Any: ...


def _g13(x: {__mul__}) -> None: ...


def _g14(x: {__mul__}) -> None: ...


def _g15(x: {__mul__}) -> None: ...


def _g16(x: {__mul__}) -> None: ...


def _g17(x: {__mul__}) -> None: ...


def _g18(x: {__mul__}) -> None: ...


def _g19(x: {__mul__}) -> None: ...


def _g20(x: {__mul__}) -> None: ...


def _g21(x: Any) -> Union[int, Any]: ...


def _g22(x: Any) -> Union[int, Any]: ...


def _g23(x: Any) -> Union[int, Any]: ...


def _g24(x: Any) -> None: ...


def _g25(x: Any) -> None: ...


def _g26(x: Any) -> Union[float, Any]: ...


def _g27(x: Any) -> Union[float, Any]: ...


def _g28(x: Any) -> None: ...


def _g29(x: Any) -> None: ...


def _g30(x: {__truediv__}) -> Union[float, Any]: ...


def _g31(x: Any) -> Union[float, Any]: ...


def _g32(x: {__len__, __lt__, __getitem__, __ge__}) -> ndarray: ...


def _g33(x: Any) -> None: ...


def _g34(x: Any) -> Union[int, Any]: ...


def _g35(x: Any) -> Union[float, Any]: ...


def _g36(x: Any) -> Union[int, Any]: ...


def _gist_heat_red(x: Any) -> Union[float, Any]: ...


def _gist_heat_green(x: Any) -> Union[int, Any]: ...


def _gist_heat_blue(x: Any) -> Union[int, Any]: ...


def _gist_yarg(x: Any) -> Union[int, Any]: ...